import: configs/mw_state_dense/corr_cpl.yaml
eval_env: mw_door-open-v2
alg_kwargs:
  alpha: 0.1
  contrastive_bias: 0.5
  bc_steps: 20000
  bc_coeff: 0.0
  bc_pool_path: /scratch/general/vast/u1472210/bc_pool/mw_door-open-v2/bc_pool.npz
  bc_pool_batch_size: 64
dataset_kwargs:
  path: /scratch/general/vast/u1472210/corr_labels/mw_door-open-v2/corr_labels.npz
  batch_size: 96
  segment_length: null
  reward_scale: 1.0
  reward_shift: 0.0
seed: 0
