import: configs/mw_state_dense/demo_cpl.yaml
eval_env: mw_plate-slide-v2
dataset_kwargs:
  path: /scratch/general/vast/u1472210/demo_labels/mw_plate-slide-v2/demo_labels_K7.npz
  batch_size: 96
  segment_length: null
  reward_scale: 1.0
  reward_shift: 0.0
seed: 0
